##' @title Sager Data
##'
##' @description
##'
##' A set of function to install and access `sager` example
##' data. Three datasets are available: a TMT11 quantitation tsv file,
##' a identification tsv file, both generated by
##' [sage](https://github.com/lazear/sage), and an mzML file that
##' contains the raw data used as input to sage.
##'
##' The data were downloaded from the ProteomeXchange project
##' [PXD016766](https://www.ebi.ac.uk/pride/archive/projects/PXD016766)
##' and processed with sage version 0.10.0 and subset to reduce their
##' size. See `inst/scripts/make-data.R` for details on how these data
##' were generated and subset.
##'
##' @section Functions:
##'
##' - `sagerMzMLData()` returns the path to the cached mzML file.
##'
##' - `sagerQuantData()` returns the path to the cached quantitation
##'    tab-separated file.
##'
##' - `sagerIdData()` returns the path to the cached identifcation
##'    tab-separated file.
##'
##' - `sagerAvailableData()` checks if the data are available in the
##'    package cache.
##'
##' - `sagerAddData(which, cache)` checks if the resources are already
##'    available in the cache. If not, data are downloaded and added
##'    to the cache.
##'
##' - `sagerRemoveData(which, cache)` removes the cached resource.
##'
##' - `sagerCache()` returns the package's cache, an object of class
##'    `BiocFileCache`.
##'
##' The `sagerMzMLData()`, `sagerQuantData()` and `sagerIdData()` use
##' the `sagerData()` function under the hood, that defined the
##' resource name and the cache. A user shouldn't have to use
##' `sagerData()`.
##'
##' The data files are downloaded and cached by `sagerAddData()` are
##' available on zenodo (10.5281/zenodo.7804639).
##'
##' @section Update locally cached data:
##'
##' The `sager` data files will occasionally be updated or new ones
##' added. These changes are documented in the NEWS.md file.
##'
##' To update your local cache, you can either delete it (it's
##' location can be found with `bfccache(sagerCache())`) to remove and
##' add the data by running `sagerRemoveData()` and `sagerAddData()`.
##'
##' @param cache Object of class `BiocFileCache`. Default for is the
##'     package's cache returned by `sagerCache()`.
##'
##' @param rname `character(1)` defining the resource name used to
##'     query `cache`.
##'
##' @importFrom BiocFileCache bfcquery BiocFileCache
##'
##' @importFrom utils packageDescription
##'
##' @export
##'
##' @rdname sagerData
##'
##' @references
##'
##'
##' - **Sage**: proteomics searching so fast it seems like
##'   magic. [https://github.com/lazear/sage](https://github.com/lazear/sage).
##'
##' - Project PXD016766:
##' [www.ebi.ac.uk/pride/archive/projects/PXD016766](https://www.ebi.ac.uk/pride/archive/projects/PXD016766).
##'
##' - Yu *et al.* 'Benchmarking the Orbitrap Tribrid Eclipse for Next
##'   Generation Multiplexed Proteomics' Anal. Chem. 2020, 92, 9,
##'   6478–6485 Publication Date:April 6, 2020
##'   [DOI:10.1021/acs.analchem.9b05685](https://doi.org/10.1021/acs.analchem.9b05685).
##'
##' - sager package test data: [DOI: 10.5281/zenodo.7804639](https://doi.org/10.5281/zenodo.7804639).
##'
##' @examples
##'
##' ## Are data already available
##' sagerAvailableData()
##'
##' sagerAvailableData("id")
##'
##' ## Remove data from cache
##' sagerRemoveData("id")
##'
##' sagerAvailableData("id")
##'
##' ## Add data (if not already available)
##' sagerAddData(c("id", "quant"))
##'
##' ## Get the path to the data
##' sagerQuantData()
##'
##' sagerIdData()
##'
##' sagerMzMLData()
##'
##' ## Data are stored in the package's cache
##' sagerCache()
sagerData <- function(cache, rname) {
    if (missing(rname))
        stop("Please provide a resource name to query the cache.")
    if (missing(cache))
        stop("Please provide BiocFile cache.")
    x <- bfcquery(cache, rname, field = "rname")
    if (!nrow(x)) {
        warning("Data not found. See ?sagerData for details.")
        return(NA)
    }
    if (nrow(x) > 1)
        stop("Found > 1 resource found. Please open an issue in",
             packageDescription("sager")$BugReports,
             "with the exact code you ran and your session information.")
    x$rpath
}

##' @export
##'
##' @rdname sagerData
##'
##' @importFrom tools R_user_dir
##'
##' @importFrom BiocFileCache BiocFileCache
sagerCache <- function() {
    cache <- tools::R_user_dir(package = "sager", which = "cache")
    BiocFileCache::BiocFileCache(cache, ask = interactive())
}

##' @export
##'
##' @rdname sagerData
sagerQuantData <- function()
    sagerData(cache = sagerCache(),
              rname = sager_rids()[["quant"]])

##' @export
##'
##' @rdname sagerData
sagerIdData <- function()
    sagerData(cache = sagerCache(),
              rname = sager_rids()[["id"]])

##' @export
##'
##' @rdname sagerData
sagerMzMLData <- function()
    sagerData(cache = sagerCache(),
              rname = sager_rids()[["mzml"]])

##' @export
##'
##' @importFrom BiocFileCache bfcadd
##'
##' @rdname sagerData
##'
##' @param which One or several of `"quant"`, `"id"` or `"mzml"`
##'     specifying what data to download.
sagerAddData <- function(which = c("quant", "id", "mzml"),
                         cache = sagerCache()) {
    which <- match.arg(which, several.ok = TRUE)
    for (i in which) {
        available <- sagerAvailableData()[i]
        if (available) {
            message("'", i, "'", " already available.")
        } else { ## Add the resource
            message("Adding '", i, "' to the package cache.")
            BiocFileCache::bfcadd(cache,
                                  rname = sager_rids()[[i]],
                                  sager_urls()[[i]])
        }
    }
    invisible(cache)
}

##' @export
##'
##' @rdname sagerData
##'
##' @importFrom BiocFileCache bfcremove bfcquery
sagerRemoveData <- function(which = c("quant", "id", "mzml"),
                            cache = sagerCache()) {
    which <- match.arg(which, several.ok = TRUE)
    for (i in which) {
        rids <- sager_rids()[[i]]
        if (i == "mzml") {
            x <- bfcquery(cache, "subset.+\\.mzML", field = "rname")
        } else {
            x <- bfcquery(cache, rids, field = "rname", exact = TRUE)
        }
        if (!nrow(x)) {
            message("Resource '", i, "' not found, none removed.")
            next()
        }
        bfcremove(cache, x$rid)
    }
    invisible(cache)
}

##' @export
##'
##' @rdname sagerData
##'
##' @importFrom BiocFileCache bfcquery
sagerAvailableData <- function(which = c("quant", "id", "mzml"),
                               cache = sagerCache()) {
    which <- match.arg(which, several.ok = TRUE)
    c(quant = sagerAvailableQuant(),
      id = sagerAvailableId(),
      mzml = sagerAvailableMzML())
}

sagerAvailableId <- function(cache = sagerCache()) {
    r_i <- bfcquery(cache, sager:::sager_rids()[["id"]], field = "rname")
    if (nrow(r_i) > 1)
        stop("Found > 1 'id' resource found.",
             "Please open an issue in",
             packageDescription("sager")$BugReports,
             "with the exact code you ran and your session information.")
    nrow(r_i) == 1
}

sagerAvailableQuant <- function(cache = sagerCache()) {
    r_i <- bfcquery(cache, sager:::sager_rids()[["quant"]], field = "rname")
    if (nrow(r_i) > 1)
        stop("Found > 1 'quant' resource found.",
             "Please open an issue in",
             packageDescription("sager")$BugReports,
             "with the exact code you ran and your session information.")
    nrow(r_i) == 1
}

sagerAvailableMzML <- function(cache = sagerCache()) {
    r_i <- bfcquery(cache, "subset.+\\.mzML", exact = FALSE)
    all(sager:::sager_rids()[["mzml"]] %in% r_i$rname )
}

## ===============================================
## Non-exported helper function

##' @title Internal functions
##'
##' @description
##'
##' - `sager_rids()` is used internally to keep track of the resource
##'   names (rname) in the package's cache. It is used in functions
##'   such as [sagerQuantData()], ... that return the path to a
##'   resource (rpath). When new data are added to the cache, their
##'   rname should be added here.
##'
##' - `sager_urls()` keeps track of the resource URLs on zenodo. It is
##'   used in [sagerAddData()] the get the URLs of the resources to be
##'   added.
##'
##' Both return named vectors.
##'
##' ChangeLog:
##'
##' - version 2: updated 'subset' data files and new config file
##' - version 3: provide 3 separate subsetted mzML files, and update
##'   quant and id files (generated from re-running sage on the mzML
##'   subsets).
##'
##'
##' @param which `character()` specifying what type of resource to
##'     return.
##'
##' @rdname sager_internal
sager_rids <- function(which = c("quant", "id", "mzml", "config")) {
    rids <- list(quant = "sager_subset_quant",
                 id = "sager_subset_id",
                 mzml = c("subset_dq_00084_11cell_90min_hrMS2_A5.mzML",
                          "subset_dq_00086_11cell_90min_hrMS2_A9.mzML",
                          "subset_dq_00087_11cell_90min_hrMS2_A11.mzML"),
                 config = "sager_subset_json")
    which <- match.arg(which, several.ok = TRUE)
    rids[which]
}

sager_urls <- function(which = c("quant", "id", "mzml", "config")) {
    urls <- list(quant = "https://zenodo.org/record/7821565/files/87fa96d942bef_quant.tsv",
                 id = "https://zenodo.org/record/7821565/files/87fa969be47cd_results.sage.tsv",
                 mzml = c("https://zenodo.org/record/7821565/files/87fa94493400b_subset_dq_00084_11cell_90min_hrMS2_A5.mzML",
                       "https://zenodo.org/record/7821565/files/87fa94493400b_subset_dq_00086_11cell_90min_hrMS2_A9.mzML",
                       "https://zenodo.org/record/7821565/files/87fa94493400b_subset_dq_00087_11cell_90min_hrMS2_A11.mzML"),
                 config = "https://zenodo.org/record/7821565/files/87fa9328f5683_results.json")
    which <- match.arg(which, several.ok = TRUE)
    urls[which]
}

sager_urls_v2 <- function(which = c("quant", "id", "mzml", "config")) {
    urls <- c(quant = "https://zenodo.org/record/7810260/files/577925b6185b3_subset_quant.tsv",
              id = "https://zenodo.org/record/7810260/files/5779264d15c02_subset_results.sage.tsv",
              mzml = "https://zenodo.org/record/7810260/files/5779224eb8e7_sager_subset_PXD016766.mzML",
              config = "https://zenodo.org/record/7810260/files/5109a34782e0b_results.json")
    which <- match.arg(which, several.ok = TRUE)
    urls[which]
}

sager_urls_v1 <- function(which = c("quant", "id", "mzml")) {
    urls <- c(quant = "https://zenodo.org/record/7804639/files/1e705d5d7e79_subset_quant.tsv",
              id = "https://zenodo.org/record/7804639/files/1e70515047b45_subset_results.sage.tsv",
              mzml = "https://zenodo.org/record/7804639/files/1e7051d5dbf58_sager_subset_PXD016766.mzML")
    which <- match.arg(which, several.ok = TRUE)
    urls[which]
}
